version: '3'


services:
  web:
    image: ahmadum01/orto-tezzi-back
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             gunicorn --bind :8000 --workers 5 configs.wsgi:application --access-logfile - --error-logfile - "
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - .env

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - "5050:80"
    logging:
      driver: none


volumes:
  db-data: