# Generated by Django 4.2 on 2023-04-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
