name: Docker deploy

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_HOST: "db"
          envkey_POSTGRES_PORT: "5432"
          envkey_POSTGRES_DB: "postgres"
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_HOST_AUTH_METHOD: "trust"
          envkey_ALLOWED_HOSTS: "*"

          file_name: .env

      - name: Copy actual docker-compose.yml and .env
        uses: appleboy/scp-action@master
        with:
          host: 46.149.73.62
          username: orto_tezzi
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          source: ".env,docker-compose.staging.yml"
          target: "~/orto_tezzi_back"

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend
        id: docker_build_backend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ahmadum01/orto_tezzi_back:latest

      - name: Trigger container update
        uses: appleboy/ssh-action@master
        with:
          host: 46.149.73.62
          username: orto_tezzi
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
                  cd ~/orto_tezzi_back && docker-compose -f docker-compose.staging.yml pull && make build_and_up