name: Lint-test

on:
  push:
    branches:
      - main
      - staging

  pull_request:
    branches:
      - main
      - staging

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ALLOWED_HOSTS: "*"
          envkey_DEBUG: "True"
          envkey_POSTGRES_DB: "postgres"
          envkey_POSTGRES_HOST: "db"
          envkey_POSTGRES_HOST_AUTH_METHOD: "trust"
          envkey_POSTGRES_PORT: 5432
          envkey_POSTGRES_USER: "postgres"

      - name: Lint
        run: docker-compose -f docker-compose.staging.yml run --rm web sh -c "make lint"

      - name: Test
        run: docker-compose -f docker-compose.staging.yml run --rm web sh -c "make test"
