# Generated by Django 4.2 on 2023-05-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsize",
            name="size",
            field=models.CharField(max_length=15),
        ),
    ]
