# Generated by Django 4.2 on 2023-04-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, null=True, to="products.productsize"
            ),
        ),
    ]
