# Generated by Django 4.2 on 2023-04-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_productsize_remove_product_size_product_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("M", "Man"), ("W", "Women"), ("C", "Common")], max_length=10
            ),
        ),
    ]
